name: Python Linter & Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Lint with pylint
        run: |
          pipenv run pylint app
      - name: Test with nose
        run: |
          pipenv run nosetests

  review:
    if: ${{ github.ref != 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination-branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Awesome PR by ${{ github.actor }}"
